language: ruby
rvm:
  - 2.4.0
  - 2.4.1
  - 2.4.2
  - 2.5.1
env:
  - CASSANDRA_VERSION=2.1.2
  - CASSANDRA_VERSION=3.0.10
  - CASSANDRA_VERSION=3.9

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get install libjna-java
  - sudo apt-get install python-support
  - sudo easy_install pyYaml
  - sudo easy_install pip
  - sudo pip install ccm

install:
  - ccm create -n 1 -v $CASSANDRA_VERSION -i 127.0.0. -s -b test-cluster
  - ccm start
  - bundle install
