language: ruby
rvm:
  - 2.3.3
env:
  - CASSANDRA_VERSION=2.1.2
  - CASSANDRA_VERSION=3.9

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get install libjna-java
  - sudo apt-get install python-support
  - sudo easy_install pyYaml
  - sudo easy_install pip
  - sudo pip install ccm

install:
  - ccm create -n 1 -v $CASSANDRA_VERSION -i 127.0.0. -s -b test-cluster
  - ccm start
  - bundle install

addons:
  code_climate:
    repo_token: 26f0cacdb10ba97b60694f2b1ad6e45e9ea723d20fcc8ed4ae9cc415952ba934